from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('property_list/', views.property_list, name="property_list"),
    path('property_type/', views.property_type, name="property_type"),
    path('property_agent/', views.agent, name='agent'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('error/', views.error, name='error'),
    path('contact/', views.contact, name='contact'),
    path('login_register_user/', views.auth_user, name='auth_user'),
    path('login_register_admin/', views.auth_admin, name='auth_admin'),
    path('logout/', views.logoutPage, name='logout'),
    path('add_tennis/', views.add_tennis, name='add_tennis'),
    path('delete_court/<int:court_id>/', views.delete_court, name='delete_court'),
    path('edit_court/<int:court_id>/', views.edit_court, name='edit_court'),
    path('detail/', views.detail, name='detail'),
    path('rent_court/<int:court_id>/', views.rent_court, name='rent_court'),
    path('checkout/', views.checkout, name='checkout'),
    path('profile/', views.profile, name='user_profile'),
    path('user_profile_edit/', views.edit_profile, name='user_profile_edit'),
    path('booking/', views.my_bookings, name='booking'),
    path('report/<int:court_id>/', views.report_court, name='report_court'),
    path('reports/', views.admin_reports, name='reports'),
    path('review/<int:court_id>/', views.add_review, name='review'),
    path('rating/<int:court_id>/', views.tennis_court_reviews, name='rating'),
    path('bookings/', views.all_user_bookings, name='bookings'),
    path('manage/', views.manage_users, name='manage_users'), 
    path('transaction_history', views.transaction_history, name='transaction_history'),
    path('booking_success', views.booking_success, name='booking_success'),
    path('top_up', views.top_up, name='top_up'),
    # path('reset/', views.request_password_reset, name='request_password_reset'),
    # path('manage_reset/', views.manage_reset_requests, name='manage_reset_requests'),
    # path('new_password/', views.set_new_password, name='set_new_password'),
    path('reset/', views.request_password_reset, name='request_password_reset'),
    path('admin_reset/', views.admin_view_password_reset_requests, name='admin_password_reset_requests'),
    path('set_new_password/<str:username>/', views.set_new_password, name='set_new_password'),
    path('check_password_reset_status/', views.check_password_reset_status, name='check_password_reset_status'),
    path('report_all_payments/', views.revenue_data, name='revenue_data'),
    path('delete_account', views.delete_account, name='delete_account'),
    path('test-media/', views.test_media),
    # Google Login
    path('google-login/', views.google_login, name='google_login'),
    # Search
    path('search/', views.search_courts, name='search_courts'),
]

