# Generated by Django 5.0.5 on 2024-12-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennis',
            name='digital',
        ),
        migrations.AddField(
            model_name='tennis',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Repairing', 'Repairing')], default='Available', max_length=10),
        ),
    ]
