# Generated by Django 5.0.5 on 2024-12-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_invoice_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
