# Generated by Django 5.0.5 on 2024-12-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_passwordresetrequest_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
