# Generated by Django 5.0.5 on 2024-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_passwordresetrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
