# Generated by Django 5.0.5 on 2024-12-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_requested_at_passwordresetrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='otp_expiration',
        ),
    ]
