# Generated by Django 5.1.11 on 2025-12-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_add_activity_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("balance", "Account Balance"),
                    ("credit_card", "Credit Card"),
                    ("momo", "Momo Wallet"),
                    ("bank_transfer", "Bank Transfer"),
                    ("vnpay", "VNPay"),
                    ("zalopay", "ZaloPay"),
                ],
                default="balance",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("balance", "Account Balance"),
                    ("credit_card", "Credit Card"),
                    ("momo", "Momo Wallet"),
                    ("bank_transfer", "Bank Transfer"),
                    ("vnpay", "VNPay"),
                    ("zalopay", "ZaloPay"),
                ],
                default="balance",
                max_length=20,
            ),
        ),
    ]
